//
//  PokemanOverviewModels.swift
//  CleanArchitecture
//
//  Created by Austin Betzer on 12/18/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum PokemanOverview {
    // MARK: Use cases

    enum Something {
        struct PokemanOverviewRequest {

        }

        struct PokemanOverviewResponse {

        }

        struct PokemanOverviewViewModel {

        }
    }
}
