//
//  PokemanOverviewWorker.swift
//  CleanArchitecture
//
//  Created by Austin Betzer on 12/18/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class PokemanOverviewWorker {
    
    func fetchPokeman(completion: @escaping) {
        APIManager.loadAllPokeman { result in
            switch result {
            case .failure(let e):
                
            case .success:
            }
        }
    }
}
