//
//  PokemanOverviewViewController.swift
//  CleanArchitecture
//
//  Created by Austin Betzer on 12/18/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PokemanOverviewDisplayLogic: AnyObject {
    func displaySomething(viewModel: PokemanOverview.Something.PokemanOverviewViewModel)
//    func displaySomethingElse(viewModel: PokemanOverview.SomethingElse.ViewModel)
}

class PokemanOverviewViewController: UIViewController, PokemanOverviewDisplayLogic {
    var interactor: PokemanOverviewBusinessLogic?
    var router: (NSObjectProtocol & PokemanOverviewRoutingLogic & PokemanOverviewDataPassing)?

    // MARK: Object lifecycle

    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }

    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }

    // MARK: - Setup Clean Code Design Pattern 

    private func setup() {
        let viewController = self
        let interactor = PokemanOverviewInteractor()
        let presenter = PokemanOverviewPresenter()
        let router = PokemanOverviewRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }

    // MARK: - Routing

    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }

    // MARK: - View lifecycle

    override func viewDidLoad() {
        super.viewDidLoad()
        fetchPokemans()
//        doSomethingElse()
    }
    
    //MARK: - receive events from UI
    
    //@IBOutlet weak var nameTextField: UITextField!
//
//    @IBAction func someButtonTapped(_ sender: Any) {
//
//    }
//
//    @IBAction func otherButtonTapped(_ sender: Any) {
//
//    }
    
    // MARK: - request data from PokemanOverviewInteractor

    func fetchPokemans() {
        let request = PokemanOverview.Something.PokemanOverviewRequest()
        interactor?.fetchPokemans(request: request)
    }
//
//    func doSomethingElse() {
//        let request = PokemanOverview.SomethingElse.Request()
//        interactor?.doSomethingElse(request: request)
//    }

    // MARK: - display view model from PokemanOverviewPresenter

    func displaySomething(viewModel: PokemanOverview.Something.PokemanOverviewViewModel) {
        //nameTextField.text = viewModel.name
    }
//
//    func displaySomethingElse(viewModel: PokemanOverview.SomethingElse.ViewModel) {
//        // do sometingElse with viewModel
//    }
}
