//
//  PokemanOverviewInteractor.swift
//  CleanArchitecture
//
//  Created by Austin Betzer on 12/18/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PokemanOverviewBusinessLogic {
    func doSomething(request: PokemanOverview.Something.Request)
//    func doSomethingElse(request: PokemanOverview.SomethingElse.Request)
}

protocol PokemanOverviewDataStore {
    //var name: String { get set }
}

class PokemanOverviewInteractor: PokemanOverviewBusinessLogic, PokemanOverviewDataStore {
    var presenter: PokemanOverviewPresentationLogic?
    var worker: PokemanOverviewWorker?
    //var name: String = ""

    // MARK: Do something (and send response to PokemanOverviewPresenter)

    func doSomething(request: PokemanOverview.Something.Request) {
        worker = PokemanOverviewWorker()
        worker?.doSomeWork()

        let response = PokemanOverview.Something.Response()
        presenter?.presentSomething(response: response)
    }
//
//    func doSomethingElse(request: PokemanOverview.SomethingElse.Request) {
//        worker = PokemanOverviewWorker()
//        worker?.doSomeOtherWork()
//
//        let response = PokemanOverview.SomethingElse.Response()
//        presenter?.presentSomethingElse(response: response)
//    }
}
