//
//  PokemanDetailsInteractor.swift
//  CleanArchitecture
//
//  Created by Austin Betzer on 12/18/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PokemanDetailsBusinessLogic {
    func doSomething(request: PokemanDetails.Something.Request)
//    func doSomethingElse(request: PokemanDetails.SomethingElse.Request)
}

protocol PokemanDetailsDataStore {
    //var name: String { get set }
}

class PokemanDetailsInteractor: PokemanDetailsBusinessLogic, PokemanDetailsDataStore {
    var presenter: PokemanDetailsPresentationLogic?
    var worker: PokemanDetailsWorker?
    //var name: String = ""

    // MARK: Do something (and send response to PokemanDetailsPresenter)

    func doSomething(request: PokemanDetails.Something.Request) {
        worker = PokemanDetailsWorker()
        worker?.doSomeWork()

        let response = PokemanDetails.Something.Response()
        presenter?.presentSomething(response: response)
    }
//
//    func doSomethingElse(request: PokemanDetails.SomethingElse.Request) {
//        worker = PokemanDetailsWorker()
//        worker?.doSomeOtherWork()
//
//        let response = PokemanDetails.SomethingElse.Response()
//        presenter?.presentSomethingElse(response: response)
//    }
}
