//
//  PokemanDetailsPresenter.swift
//  CleanArchitecture
//
//  Created by Austin Betzer on 12/18/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PokemanDetailsPresentationLogic {
    func presentSomething(response: PokemanDetails.Something.Response)
}

class PokemanDetailsPresenter: PokemanDetailsPresentationLogic {
    weak var viewController: PokemanDetailsDisplayLogic?

    // MARK: Parse and calc respnse from PokemanDetailsInteractor and send simple view model to PokemanDetailsViewController to be displayed

    func presentSomething(response: PokemanDetails.Something.Response) {
        let viewModel = PokemanDetails.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
//
//    func presentSomethingElse(response: PokemanDetails.SomethingElse.Response) {
//        let viewModel = PokemanDetails.SomethingElse.ViewModel()
//        viewController?.displaySomethingElse(viewModel: viewModel)
//    }
}
